- name: Install packages
  become: true
  pacman:
    name:
      - nvidia-settings
      - vulkan-mesa-layers
      - nvidia-prime

#- name: Enable and start nvidia-powerd service
#  become: true
#  systemd_service:
#    name: "nvidia-powerd.service"
#    state: started
#    enabled: true
#    daemon_reload: true
