- name: Install packages
  become: true
  pacman:
    name:
      - nsz

- name: Download emulators from dropbox
  shell: |
    rclone copy db:Apps/{{ item }} {{ home }}/{{ archive_1tb_name }}/Apps/
    chmod 755 {{ home }}/{{ archive_1tb_name }}/Apps/{{ item }}
  args:
    creates: "{{ home }}/{{ archive_1tb_name }}/Apps/{{ item }}"
  loop:
    - Ryujinx.AppImage
    - Citron.AppImage

- name: Copy .desktop files
  template:
    src: "templates/{{ item }}.desktop"
    dest: "{{ home}}/.local/share/applications/"
  loop:
    - ryujinx
    - citron

- name: Create folder for nsz prod keys
  file:
    state: directory
    path: "{{ home }}/.switch"

- name: Copy firmware and prod keys
  command: "rclone copy db:Apps/nintendoswitch/ {{ home }}/.switch/"
  args:
    creates: "{{ home }}/.switch/prod.keys"
